name: Run code checks

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  code-checks:
    runs-on: ubuntu-latest

    env:
      ELIMAR_DATABASE_URL: 'mock'

    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Use Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install requirements
        run: pip install -r requirements/local.txt

      - name: Check black
        run: black . --check

      - name: Check mypy
        run: find . -name '*.py' | grep -v migrations | xargs mypy
